version: '3.6'

services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - "3307:3307"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data: